### ISSUE TITLE
Aether Object Protection Issues

### ISSUE THREAD

**Issue by Crypt0s** [codecombat/aether#122]
It is possible to bypass the API Protections and modify thang attributes using the Javascript Object keyword to add or change property values directly with .defineProperty()

There are other Object functions which are destructive to API security which could be abused including .freeze() and potentially .__defineSetter__().  The lodash framework may also expose similar functionality to users but has not been tested (yet).

These functions are available as Javascript in every language in codecombat.

Potential Mitigations:
Determine if a simulation is attempting to modify an object outside of it's purview by hashing the value of a non-changeable attribute before the chooseAction() code is ran then comparing the hash at the end and using that to determine if chooseAction() modified the value.  This would require simulations to take place on a central server (not feasible)

Blacklist Object functions which modify object prototypes.  Overwrite Object to disallow these non-safe functions in the same coffeescript where the rest of the globals are defined.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
