### ISSUE TITLE
Aether tmp Variable Collisions

### ISSUE THREAD

**Issue by Crypt0s** [codecombat/aether#123]
Defining the value of any global variable named tmp or tmp# (where # is an integer) will crash the transpiler with the following error:

chooseAction() definition:
> tmp1 = 'crashme';

Error:
>JS_WALA couldn't handle m {type: "Program", start: 0, end: 639, loc: d, body: Array[1]} 
>gave error: TypeError: Cannot read property 'attr' of null 

A cursory review of the Aether demo on aetherjs.com suggests this may be due to collisions with tmp variables defined by the transpiler itself.  

This bug does not seem to adversely affect gameplay on Codecombat

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
