### ISSUE TITLE
Possible Clojure `let` problem

### ISSUE THREAD

**Issue by nwinter** [codecombat/aether#124]
Some bug reports from [the forum](http://discourse.codecombat.com/t/the-final-kithmaze/1161/7):

``` clojure
(let [enemy (.findNearestEnemy this)]
         (.attack this enemy)
         (.attack this enemy)
)
```

> It happened to me too, I had to write `(.attack this (.findNearestEnemy this))` every time, but to be honest it seems like a bug to me.

I wonder what would cause the first code to fail and the second code to work. @vickychijwani any ideas off the top of your head?

**Comment by Vlevo** [comment]
This "issue" has been closed but the problem remains (or has come back)
[Forum post](http://discourse.codecombat.com/t/help-only-killing-1-ogre-in-patrol-buster-with-clojure/2817/10)
