### ISSUE TITLE
startTime issue in Waves

### ISSUE THREAD

**Issue by stephenstgo** [codecombat/aether#131]
I am having an issue with a Thang Referee trying to start a Wave. It seems that applying a startTime to the Wave causes the whole level to not load, no matter what value is in the startTime. I am sure it is the startTime that is causing this because I tried switching every single piece of my code.

**Comment by nwinter** [comment]
Can you check the JS console to see if it's spitting out any error messages about not being able to spawn the wave, maybe due to a misconfigured wave or not matching the Builds/Spawns dependent ThangTypes?

**Comment by nwinter** [comment]
Actually, let's discuss in CodeCombat repo version of this issue.
