### ISSUE TITLE
Simple loop not implemented for Clojure

### ISSUE THREAD

**Issue by razvan-panda** [codecombat/aether#147]
Getting this error every time when trying to use a function as value (CodeCombat). Not sure what is going on as there is not obvious loop run defined.

More details: https://github.com/vickychijwani/closer.js/issues/15

**Comment by razvan-panda** [comment]
Related: https://github.com/codecombat/aether/issues/143#issuecomment-106598321

**Comment by nwinter** [comment]
Simple loops are deprecated now anyway.
