### ISSUE TITLE
Invalid strict pragma

### ISSUE THREAD

**Issue by UltCombo** [codecombat/aether#149]
In the `obviouslyCannotTranspile` function, the `'use strict';` pragma is [currently misspelled as `'use strict;'`](https://github.com/codecombat/aether/blob/9f2f9e41da97187ea1ff99d01432f6f82b76dd42/src/languages/javascript.coffee#L26) and thus ignored (it is interpreted as a mere string literal).

The invalid pragma should either be removed (keeping the current behavior) or fixed.
I believe CodeCombat runs user code in non-strict mode, so I believe we can just remove the invalid pragma.

**Comment by nwinter** [comment]
Hehe, oops.

Let's test it both ways and see if there are any differences.

**Comment by UltCombo** [comment]
Strict mode has more early errors:

```js
(function() {
    'use strict'; throw 0;
    function f(a, a){}
}());
// Uncaught SyntaxError: Strict mode function may not have duplicate parameter names
```

```js
(function() {
    'use strict'; throw 0;
    016;
}());
// Uncaught SyntaxError: Octal literals are not allowed in strict mode.
```

The samples above run fine in CodeCombat (which runs code in loose mode), so we should probably just remove the invalid pragma.

Or we can add a property/constructor option to tell Aether whether code should be treated as strict or not.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter–we are now in strict mode.

**Comment by UltCombo** [comment]
Nice! I believe this is the best way going forward... I was just worried that this change would break existing code—several mistakes that are silently ignored in sloppy mode throw errors in strict mode.

But yeah, I guess virtually all affected code would be incorrect and displaying warnings. Backwards compatibility with buggy code does not seem worth holding back improvements to the engine.
