### ISSUE TITLE
Protecting RegExp builtin errors

### ISSUE THREAD

**Issue by trotod** [codecombat/aether#154]
http://discourse.codecombat.com/t/play-button-not-responsive-on-lvl-1/1592/5

[Latest spec](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-properties-of-the-regexp-prototype-object) says that `RegExp.prototype` is an ordinary object, which makes this error in bleeding edges of Chrome:

    Uncaught TypeError: RegExp.prototype.global getter called on non-RegExp object

**Comment by nwinter** [comment]
@basicer can you fix this? I guess something needs to change [here](https://github.com/codecombat/aether/blob/master/src/protectBuiltins.coffee#L30).

**Comment by nwinter** [comment]
Fixed in 68d10c6
