### ISSUE TITLE
Don't use API protection on user-defined inner functions

### ISSUE THREAD

**Issue by nwinter** [codecombat/aether#48]
See [this thread](http://discourse.codecombat.com/t/functions-passing-parameters-by-value/705). Basically, things going in and out of function boundaries have API protection applied during the transpiler, which means you can't write their properties. We probably don't need it for this case, since you defined your own function, so any argument you passed to it is already protected.

```javascript
function test(arg)
{
    arg.id = 3;
}
var o = {id:1};
test(o);
this.say("id: " + o.id"); // always says id: 1
```

**Comment by baerrach** [comment]
Is this documented somewhere? I've been banging my head against this problem for a few days and it was only when I started boiling it down to a simple repeatable test case that I could work out the problem.

**Comment by nwinter** [comment]
Should be fixed soon when we default to using the new interpreter, I think.

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter.
